[package]
name = "astrograph-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Astrograph analysis CLI."

[dependencies]
anyhow = "1.0"
astrograph-engine = { path = "../astrograph-engine" }
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
